ktor {
    deployment {
        port = 8080
    }
    application {
        modules = ["com.financetracker.ApplicationKt.module"]
    }
}

database {
    url      = ${?DB_URL}
    user     = ${?DB_USER}
    password = ${?DB_PASSWORD}
    poolSize = 10
}

app {
    version = "dev"
    version = ${?APP_VERSION}
}
