ktor {
    deployment {
        port = 8080
    }
    application {
        modules = ["com.financetracker.ApplicationKt.module"]
    }
}

database {
    url               = ${?DB_URL}
    user              = ${?DB_USER}
    password          = ${?DB_PASSWORD}
    poolSize          = 10
    migrationsLocation = "classpath:db/migration"
    migrationsLocation = ${?DB_MIGRATIONS_LOCATION}
}

app {
    version = "dev"
    version = ${?APP_VERSION}
}
